name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.x'

      - name: Install Bun (Linux/macOS)
        run: |
          curl -fsSL https://bun.sh/install.sh | bash -s
          echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Build project
        run: |
          ~/.bun/bin/bun build src/routes/+page.svelte

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.x'

      - name: Install Bun (Windows)
        run: powershell -c "irm bun.sh/install.ps1 | iex"

      - name: Build project
        run: bun build src/routes/+page.svelte

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build

  deploy:
    needs: [build, build-windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download production artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
